### ISSUE TITLE
Issue while adding samwat with timedelta

### ISSUE THREAD

**Issue by saroz014** [poudel/bikram#14]
* Python Bikram Samwat version: 2.1.0
* Python version: 3.8.2
* Operating System: Linux Mint 19

### Description

Adding samwat object with timedelta object didn't return the correct output.

### What I Did

```
samwat(2000, 2, 2) + timedelta(days=1)
Out[1]: samwat(2000, 10, 21)
```
Expected output --> samwat(2000, 2, 3)

**Comment by acpmasquerade** [comment]
verified

In [3]: from datetime import timedelta

In [4]: bikram.samwat(2000, 2, 2)
Out[4]: samwat(2000, 2, 2)

In [5]: bikram.samwat(2000, 2, 2) + timedelta(days=1)
Out[5]: samwat(2000, 10, 21)

**Comment by poudel** [comment]
I suspect this happens because the 2000 BS is the lowest year this library supports. Literally an edge case. 

Unfortunately, I don't have the time to fix this at the moment. 

Please use this library instead: https://github.com/dxillar/nepali-datetime

It has a pythonic API and supports far more years.
